name: CSV_CLEANER

on:
  push:
    branches:
      ["main"]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_pass }}


      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.open_ai }}" >> SRC/init.env
          
        
      - name: Start containers
        run: docker compose up -d --build

      - name: Sleep for 10s
        run: sleep 10

      - name: Stop containers
        if: always()
        run: docker compose down

         

        

          
          
      

          